name: First CL

on:
  push:
    branches:
      - main

  pull_request: 
    branches:
      - main

  workflow_dispatch: 
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running tests"
          echo "The test should now pass"
          echo "This is where the head is : ${{github.head_ref}}"
          ls -lahr
          exit 0

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project"



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying code to production"
      
  
  
[![First CL](https://github.com/jwokocha/practice-github-actions/actions/workflows/main.yml/badge.svg)](https://github.com/jwokocha/practice-github-actions/actions/workflows/main.yml)
