name: First CL

on:
  push:
    branches:
      - main

  pull_request: 
    branches:
      - main

  workflow_dispatch: 
   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running tests"
          echo "The test should now pass"
          echo "This is where the head is : ${{github.head_ref}}"
          ls -lahr
          exit 0

      - name: Show GitHub Context
        run: |
          echo "Event Name : ${{ github.event_name }}"
          echo "Git Ref    : ${{ github.ref }}"
          echo "Head Ref   : ${{ github.head_ref }}"
          echo "Base Ref   : ${{ github.base_ref }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project"



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "deploying code to production"
          echo "The deployment is complete"
